"""Database creation

Revision ID: 8b64f1d16118
Revises:
Create Date: 2024-12-13 23:52:16.557170

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b64f1d16118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('result_uuid', sa.UUID(), nullable=False),
    sa.Column('stdout', postgresql.BYTEA(), nullable=True),
    sa.Column('stderr', postgresql.BYTEA(), nullable=True),
    sa.Column('params', sa.String(), nullable=False),
    sa.Column('engine', sa.Text(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('result_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
